import {interiorVideo} from './video.mjs';
import {serviceRibbon} from './ribbon.mjs';
const E=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const direction={
 interior:{word:'SPACE',title:['공간의 완성도를,','브랜드의 경쟁력으로.'],sample:'오래 머물고 싶은 공간',brand:'SPACE / STUDIO',label:'공간의 변화가 보이는 시공 포트폴리오',items:['주거 리모델링','상업 공간','프로젝트 기록'],statement:'좋은 시공을 알아보는 고객에게.',explain:'완성 사진에 공정과 선택의 이유를 더합니다. 지역 검색에서 시공 사례를 만나고, 자신의 공간을 이야기하는 상담으로 이어지도록 설계합니다.'},
 cleaning:{word:'CARE',title:['꼼꼼한 작업이,','선택받는 이유가 되도록.'],sample:'일상의 쾌적함을 만드는 일',brand:'CLEAR / CARE',label:'작업 기준이 분명한 청소 브랜드 홈페이지',items:['입주·이사 청소','상가·정기 관리','작업 범위 안내'],statement:'가격보다 먼저, 일하는 기준을.',explain:'고객이 가장 궁금해하는 작업 범위부터 설명합니다. 실제 현장 기록과 포함·제외 항목, 예약 전 확인 사항을 정리해 상담의 출발점을 바꿉니다.'},
 demolition:{word:'BUILD',title:['현장의 신뢰를,','다음 수주로 연결합니다.'],sample:'다음 시작을 위한 정확한 마무리',brand:'GROUND / WORKS',label:'현장 조건과 작업 범위가 보이는 철거 홈페이지',items:['상가 원상복구','내부·부분 철거','현장 문의'],statement:'장비보다 먼저, 현장을 읽는 방식.',explain:'면적과 공종, 반출 동선과 인계까지. 가격 한 줄로 설명할 수 없는 현장의 조건을 정리하고, 필요한 정보를 갖춘 문의로 연결합니다.'},
 funeral:{word:'RESPECT',title:['차분한 안내가,','깊은 신뢰로 이어지도록.'],sample:'마음을 다하는 공간과 안내',brand:'온결 / MEMORIAL',label:'시설과 방문 정보가 명확한 장례식장 홈페이지',items:['빈소·시설 안내','주차·오시는 길','이용 절차'],statement:'가장 필요한 정보가, 가장 먼저.',explain:'시설을 알아보는 가족과 방문을 준비하는 조문객의 질문은 다릅니다. 각자가 필요한 연락처와 위치, 이용 정보를 편안하게 찾을 수 있도록 구성합니다.'},
 insurance:{word:'TRUST',title:['명확한 설명이,','상담의 시작이 됩니다.'],sample:'내 상황을 이해하는 상담',brand:'BALANCE / PARTNERS',label:'운영 주체와 상담 분야가 선명한 브랜드 홈페이지',items:['소속·상담 분야','질문 중심 칼럼','상담 준비 안내'],statement:'많이 말하기보다, 정확히 전합니다.',explain:'운영 주체와 상담 분야, 적용 조건을 명확하게 보여줍니다. 콘텐츠 검수와 업데이트 과정을 함께 설계해 설명의 일관성을 지킵니다.'},
 shortform:{word:'MOTION',title:['짧게 보여주고,','오래 기억되도록.'],sample:'한 장면에서 시작되는 이야기',brand:'FRAME / STUDIO',label:'기획의 의도가 보이는 영상 포트폴리오',items:['브랜드 인터뷰','서비스 소개','현장 스케치'],statement:'조회 다음에 무엇이 남는가.',explain:'한 편마다 고객의 질문 하나에 답합니다. 영상의 도입과 메시지, 프로필과 홈페이지의 연결까지 기획해 시청 이후의 행동을 만듭니다.'}
};
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>';
const chatIcon='<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 4C8.3 4 2 8.6 2 14.3c0 3.7 2.7 7 6.7 8.8L7 29l7.1-4.4c.6.1 1.3.1 1.9.1 7.7 0 14-4.6 14-10.4C30 8.6 23.7 4 16 4Z"/></svg>';
const phoneIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-5-2-2 2c-3.1-1.4-5.6-3.9-7-7l2-2-2-5Z"/></svg>';
export function contactDock(chat){return `<nav class="contact-dock" aria-label="빠른 상담"><a class="dock-kakao" href="${chat}" target="_blank" rel="noopener noreferrer" aria-label="카카오톡 상담 새 창">${chatIcon}<span>카카오톡<small>상담하기 ↗</small></span></a><a class="dock-phone" href="tel:01055010152" aria-label="전화 상담 010-5501-0152">${phoneIcon}<span>전화 상담<small>010-5501-0152</small></span></a><a class="dock-top" href="#main" aria-label="맨 위로">↑<span>TOP</span></a></nav>`;}
export function agencyHero(k,s,d,chat){const v=direction[k];return `<section class="agency-hero"><div class="wrap"><div class="agency-kicker"><span>ARB COMPANY — ${k.toUpperCase()} MARKETING</span><span class="kicker-right">STRATEGY / DESIGN / GROWTH</span></div><div class="agency-heading"><div><p class="agency-eyebrow">${E(d.eyebrow)}</p><h1>${v.title.map(t=>`<span>${E(t)}</span>`).join('')}</h1></div><div class="agency-intro"><p>${E(s.d)}</p><a class="agency-cta" href="${chat}">프로젝트 상담하기 ${arrow}</a><a class="agency-work-link" href="#design">디자인 방향 살펴보기 ↓</a></div></div><div class="hero-canvas"><img src="/assets/subsites/${s.im}" alt="${E(s.n)} 디자인 방향을 표현한 콘셉트 이미지" width="1672" height="941" fetchpriority="high">${k==='interior'?interiorVideo():''}<div class="canvas-shade"></div><div class="canvas-label"><span>BUILT AROUND YOUR BUSINESS</span><strong>${E(v.word)}<i>by arb.</i></strong></div><div class="canvas-bottom"><span>${E(v.label)}</span><span>AI 제작 콘셉트 ${k==='interior'?'영상':'이미지'}</span></div><a class="canvas-arrow" href="#design" aria-label="디자인 구성 예시 보기">${arrow}</a></div><div class="agency-capabilities"><span>고객이 발견하고,<br>신뢰하고, 문의하기까지.</span><ul>${['홈페이지 제작','검색·칼럼 콘텐츠','광고 랜딩 설계','상담 동선'].map(t=>`<li>${t}</li>`).join('')}</ul></div></div></section>${serviceRibbon(s,d)}<section class="agency-statement"><div class="wrap statement-grid"><span class="overline">YOUR BUSINESS, CLEARLY.</span><div><h2>${E(v.statement)}</h2><p>${E(v.explain)}</p><div class="statement-flow"><span>검색과 유입</span><b>↗</b><span>내용과 신뢰</span><b>↗</b><span>문의와 상담</span></div></div></div></section>`;}
export function designShowcase(k,s,d){const v=direction[k];return `<section class="design-section" id="design"><div class="wrap"><div class="design-heading"><div><span class="overline">DESIGNED FOR YOUR INDUSTRY</span><h2>브랜드의 인상부터,<br>문의하는 순간까지.</h2></div><p>${E(d.detail)}<br>PC와 모바일에 맞춰 정보의 크기와 순서를 설계합니다.</p></div><div class="showcase-toolbar"><span>01 / ${k.toUpperCase()} WEBSITE CONCEPT</span><div role="group" aria-label="디자인 예시 화면 크기"><button type="button" data-demo-view="desktop" aria-pressed="true">PC 화면</button><button type="button" data-demo-view="mobile" aria-pressed="false">모바일 화면</button></div></div><div class="showcase-stage"><div class="site-concept"><div class="concept-chrome"><i></i><i></i><i></i><span>DESIGN CONCEPT · 가상 브랜드</span></div><div class="concept-nav"><b>${E(v.brand)}</b><span>브랜드 소개　서비스　문의</span><i>상담 문의 ↗</i></div><div class="concept-hero"><img src="/assets/subsites/${s.im}" alt="" width="1672" height="941" loading="lazy"><div><small>${E(v.items[0])} · ${E(v.items[1])}</small><h3>${E(v.sample)}</h3><p>${E(v.label)}</p><span class="concept-button">자세히 알아보기 ↗</span></div></div><div class="concept-bottom">${v.items.map((t,i)=>`<div><small>0${i+1}</small><strong>${E(t)}</strong><span>→</span></div>`).join('')}</div><div class="concept-mobile-bar"><span>전화 상담</span><span>카카오톡 상담</span></div></div></div><div class="showcase-caption"><span>DESIGN DIRECTION / ${E(s.n)}</span><p>디자인 방향을 보여주기 위한 가상 브랜드 예시입니다. 실제 고객사 작업물이나 성과 자료가 아닙니다.</p></div>${k==='interior'?`<div class="inspiration-panel"><div><span class="overline">SPACE IN MOTION</span><h3>사진 한 장에서,<br>공간의 경험으로.</h3><p>빛과 소재, 공간의 깊이를 영상으로 전달합니다.</p><small>AI 제작 콘셉트 영상 · 실제 시공 실적이 아닙니다.</small></div><video controls muted playsinline preload="none" poster="/assets/subsites/interior-hero.png" aria-label="인테리어 영상 연출 예시"><source src="/assets/subsites/interior-inspiration.mp4" type="video/mp4"></video></div>`:''}<div class="design-notes">${[['브랜드의 인상','업종과 서비스가 선명하게 읽히는 첫 화면'],['읽히는 콘텐츠',d.deliverables[0]],['끊기지 않는 상담','PC 오른쪽 · 모바일 하단 고정 상담 버튼']].map((x,i)=>`<div><span>0${i+1}</span><h3>${E(x[0])}</h3><p>${E(x[1])}</p></div>`).join('')}</div></div></section>`;}
