import {columnBoard,paragraphs,inline} from './editorial.mjs';
import {marketingServices,toolEntry,toolDialog} from './marketing.mjs';
import {sites} from './sites.mjs';
import {studio} from './design.mjs';
import {diagnostics} from './diagnosis.mjs';
import {articles} from './articles.mjs';
import {agencyHero,designShowcase,contactDock} from './agency.mjs';
export {sites,articles};
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chat='https://pf.kakao.com/_wxjxiSX/chat';
const list=xs=>xs.map(x=>`<li>${esc(x)}</li>`).join('');
const scriptJSON=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const companyFooter=`<section class="contact-section" id="contact"><div class="wrap contact-grid"><div><span class="overline">LET’S TALK</span><h2>지금 운영하는 방식부터<br>함께 살펴보겠습니다.</h2><p>현재 홈페이지와 보유 자료를 알려주시면 필요한 작업부터 정리해드립니다.</p></div><div class="contact-options"><a href="${chat}"><small>KAKAO</small><strong>카카오톡 상담 ↗</strong></a><a href="tel:01055010152"><small>PHONE</small><strong>010-5501-0152</strong></a><a href="mailto:20230508@aubcompany.com"><small>EMAIL</small><strong>20230508@aubcompany.com</strong></a><p><small>전화 상담 평일 09:00–18:00<br>업무 시간 외에는 카카오톡으로 남겨주세요.</small></p></div></div></section><footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand-mark" href="https://aubcompany.com/">arb.</a><p>아비컴퍼니 · ARB COMPANY</p></div><div><p>대표 오경록 · 사업자등록번호 844-22-01736</p><p>본사 — 전북특별자치도 전주시 완산구 아중로 33,<br>전주정보문화산업진흥원 C동 302호</p><p>서울사무소 — 서울특별시 송파구 가락로 114 신우빌딩 6층 627호</p><p><a href="tel:01055010152">010-5501-0152</a> · <a href="mailto:20230508@aubcompany.com">20230508@aubcompany.com</a></p><div class="footer-links"><a href="https://aubcompany.com/">회사 소개 ↗</a><a href="${chat}">카카오톡 채널</a></div></div></div><div class="footer-bottom"><span>© 2026 ARB COMPANY.</span><a href="#main">맨 위로 ↑</a></div></div></footer><div class="mobile-contact"><a href="tel:01055010152">전화 상담</a><a href="${chat}">카카오톡 상담 ↗</a></div><aside class="review-toast" id="review-toast" aria-label="기존 아비컴퍼니 고객 후기" hidden><button type="button" id="review-close" aria-label="후기 닫기">×</button><small>아비컴퍼니 기존 고객 후기 · 전문직</small><blockquote id="review-text"></blockquote><p id="review-author"></p><a href="https://aubcompany.com/">기존 홈페이지 후기 보기 ↗</a></aside>`;
function diagnosis(k){const qs=diagnostics[k];return `<section class="section diagnosis" id="diagnosis"><div class="wrap"><div class="section-heading"><div><span class="overline">WEBSITE CHECK</span><h2>우리 홈페이지,<br>어디부터 바꿀까요?</h2></div><div><p>검색·콘텐츠·상담 동선을 5개 질문으로 점검합니다. 답변에 따라 우선 점검 항목을 제안합니다.</p><small>개인정보를 받지 않는 자가진단입니다. 생성형 AI 상담이 아니며 답변은 서버로 보내지 않습니다.</small></div></div><form id="diagnosis-form"><div class="diagnosis-questions">${qs.map((q,i)=>`<fieldset data-tip="${esc(q[1])}"><legend><span>0${i+1}</span> ${esc(q[0])}</legend><label><input type="radio" name="q${i}" value="yes" required> 예</label><label><input type="radio" name="q${i}" value="no"> 아직 아니요</label></fieldset>`).join('')}</div><button class="button" type="submit">점검 결과 보기 ↗</button><div id="diagnosis-result" hidden tabindex="-1" role="status"></div></form></div></section>`;}
function motion(s){return `<div class="motion-panel"><div class="motion-heading"><span>CONTENT IN MOTION</span><button class="motion-toggle" type="button" aria-pressed="false">움직임 멈춤</button></div><div class="motion-stages">${s.c.map((x,i)=>`<div class="motion-stage"><b>0${i+1}</b><span>${esc(x[0])}</span><i aria-hidden="true"></i></div>`).join('')}</div><p>콘텐츠 구성 과정을 보여주는 모션그래픽</p></div>`;}
function card(k,a,link){return `<a class="article-card" href="${link('/column/'+a.slug+'/')}"><img src="/assets/subsites/${sites[k].im}" alt="" width="1672" height="941" loading="lazy"><div><span class="meta">${esc(a.category)} · ${a.datePublished}</span><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><span class="text-link">칼럼 읽기 ↗</span></div></a>`;}
export function renderSite(k,{path='/',previewBase='',notFound=false}={}){
 const s=sites[k],d=studio[k],posts=articles[k]||[],a=posts.find(x=>path===`/column/${x.slug}/`),isList=path==='/column/';
 const link=p=>previewBase+p,canonical=`https://${k}.aubcompany.com${path}`;
 const title=notFound?'페이지를 찾을 수 없습니다':a?a.title:isList?`${s.n} 칼럼`:`${s.n} · 홈페이지 제작`;
 const desc=a?.description||s.d;
 const org={'@type':'Organization','@id':`https://${k}.aubcompany.com/#organization`,name:'아비컴퍼니',url:'https://aubcompany.com/',telephone:'+82-10-5501-0152',email:'20230508@aubcompany.com',sameAs:[chat],address:{'@type':'PostalAddress',addressCountry:'KR',addressRegion:'전북특별자치도',addressLocality:'전주시 완산구',streetAddress:'아중로 33, 전주정보문화산업진흥원 C동 302호'}};
 const graph=[org,{'@type':'WebSite',name:`아비컴퍼니 ${s.n}`,url:`https://${k}.aubcompany.com/`,publisher:{'@id':org['@id']}}];
 if(a)graph.push({'@type':'Article',headline:a.title,description:a.description,datePublished:a.datePublished+'T09:00:00+09:00',dateModified:a.dateModified+'T09:00:00+09:00',author:{'@type':'Organization',name:'아비컴퍼니',url:'https://aubcompany.com/'},publisher:{'@id':org['@id']},mainEntityOfPage:canonical,image:`https://${k}.aubcompany.com/assets/subsites/${s.im}`});
 else if(!isList&&!notFound)graph.push({'@type':'Service',name:s.n,url:canonical,description:s.d,provider:{'@id':org['@id']}});
 const nav=`<a class="skip" href="#main">본문 바로가기</a>${previewBase?'<div class="preview-banner">디자인 미리보기 · 검색에 노출되지 않는 확인용 주소입니다.</div>':''}<header class="nav"><div class="wrap nav-inner"><a class="brand" href="${link('/')}"><span class="brand-mark">arb.</span><span class="brand-text">${s.n}<small>아비컴퍼니</small></span></a><button type="button" class="menu-button" aria-controls="site-menu" aria-expanded="false">메뉴</button><nav class="nav-links" id="site-menu" aria-label="주 메뉴"><a href="${link('/')}#marketing">마케팅 서비스</a><a href="${link('/')}#process">진행 방식</a><a href="${link('/')}#design">디자인 예시</a><a href="${link('/column/')}">칼럼 게시판</a><a href="${link('/')}#marketing-diagnosis">무료 진단</a><a href="${chat}" class="nav-cta">카카오톡 상담 ↗</a></nav></div></header>`;
 let body='';
 if(notFound)body=`<main id="main" class="wrap section"><span class="overline">404</span><h1>페이지를 찾을 수 없습니다.</h1><a class="button" href="${link('/')}">홈으로</a></main>`;
 else if(a)body=`<main id="main"><header class="page-intro"><div class="wrap"><nav class="breadcrumbs" aria-label="현재 위치"><a href="${link('/')}">홈</a><span>/</span><a href="${link('/column/')}">칼럼 게시판</a></nav><h1>${esc(a.title)}</h1><p class="hero-description">${esc(a.description)}</p><div class="meta">아비컴퍼니 · ${esc(a.category)} · 발행 ${a.datePublished} · 수정 ${a.dateModified}</div></div></header><div class="wrap reading-layout"><aside class="toc"><details><summary>이 글의 순서</summary><ol>${a.sections.map((v,i)=>`<li><a href="#section-${i}">${esc(v.heading)}</a></li>`).join('')}</ol></details></aside><article class="reading"><div class="summary-box"><strong>먼저 확인할 내용</strong><ul>${list(a.summary)}</ul></div>${a.sections.map((v,i)=>`<section id="section-${i}"><h2>${esc(v.heading)}</h2>${paragraphs(v.paragraphs)}</section>`).join('')}<div class="checklist"><strong>적용 전 체크리스트</strong><ul>${list(a.checklist)}</ul></div><div class="author"><b>아비컴퍼니</b><p>업종별 홈페이지와 콘텐츠의 구성·운영 방법을 정리합니다.</p></div><div class="article-return"><a class="text-link" href="${link('/column/')}">← 칼럼 목록</a></div></article></div></main>`;
 else if(isList)body=`<main id="main"><header class="page-intro"><div class="wrap"><nav class="breadcrumbs"><a href="${link('/')}">홈</a><span>/ 칼럼 게시판</span></nav><span class="overline">JOURNAL</span><h1>${s.n} 칼럼 게시판</h1><p class="hero-description">${d.detail} 홈페이지 제작과 마케팅 운영에 필요한 글을 찾아보세요.</p><a class="text-link" href="${link('/rss.xml')}">RSS 구독 ↗</a></div></header>${columnBoard(k,posts,link)}</main>`;
 else body=`<main id="main">${agencyHero(k,s,d,chat)}${designShowcase(k,s,d)}${marketingServices(k)}<section class="section" id="services"><div class="wrap"><div class="section-heading"><div><span class="overline">01 / OUR APPROACH</span><h2>${esc(s.p)}</h2></div><p>${esc(s.x)}</p></div><div class="service-grid">${s.c.map((v,i)=>`<article class="service-item"><span class="service-no">0${i+1}</span><h3>${esc(v[0])}</h3><p>${esc(v[1])}</p><div class="deliverable">제작 범위 · ${esc(d.deliverables[i])}</div></article>`).join('')}</div></div></section><section class="section example"><div class="wrap example-grid"><div><span class="overline">02 / CONTENT DESIGN</span><h2>${esc(d.exampleTitle)}</h2><p>${esc(d.detail)}</p><a href="${link('/column/')}" class="text-link">콘텐츠 운영 칼럼 보기 ↗</a></div><div><div class="example-board"><div class="board-top"><span>ARB / EDITORIAL NOTE</span><span>구성 예시</span></div><div class="board-title">${esc(d.example[0])}</div><div class="board-row"><span>01</span><div>${esc(d.example[1])}</div></div><div class="board-row"><span>02</span><div>${esc(d.example[2])}</div></div><p class="board-note">기획 설명용 예시이며 실제 고객 실적이 아닙니다.</p></div>${motion(s)}</div></div></section><section class="section" id="process"><div class="wrap"><div class="section-heading"><div><span class="overline">03 / WORKING TOGETHER</span><h2>자료를 살피고,<br>우선순위를 정합니다.</h2></div><p>필요한 페이지와 콘텐츠 범위를 먼저 합의합니다. 일정과 견적은 보유 자료, 제작 범위와 운영 조건을 확인한 뒤 안내합니다.</p></div><ol class="process-list">${s.st.map((v,i)=>`<li><b>0${i+1}</b><h3>${esc(v)}</h3><p>${['현재 자료와 운영 상태를 함께 확인합니다.','고객이 궁금해하는 정보와 전달 순서를 정합니다.','합의한 범위의 화면과 콘텐츠를 제작·검수합니다.','모바일 사용성과 검색 수집 설정을 점검합니다.','유입과 문의 기록으로 개선 항목을 정합니다.'][i]}</p></li>`).join('')}</ol></div></section><section class="section journal"><div class="wrap"><div class="journal-heading"><div><span class="overline">JOURNAL</span><h2>운영에 도움이 되는 글</h2></div><a class="text-link" href="${link('/column/')}">전체 칼럼 ↗</a></div>${posts.slice(0,2).map(x=>card(k,x,link)).join('')}</div></section>${toolEntry(k)}<section class="section"><div class="wrap faq-grid"><div><span class="overline">FAQ</span><h2>상담 전에<br>많이 묻는 질문</h2></div><div class="faq-list">${s.f.map(v=>`<details><summary>${esc(v[0])}</summary><p>${esc(v[1])}</p></details>`).join('')}</div></div></section></main>`;
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | 아비컴퍼니</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="${previewBase||notFound?'noindex,follow':'index,follow,max-image-preview:large,max-snippet:-1'}"><link rel="canonical" href="${canonical}"><link rel="icon" href="https://aubcompany.com/favicon.svg" type="image/svg+xml"><meta property="og:type" content="${a?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="아비컴퍼니 ${s.n}"><meta property="og:image" content="https://${k}.aubcompany.com/assets/subsites/${s.im}"><meta name="twitter:card" content="summary_large_image"><link rel="alternate" type="application/rss+xml" title="${s.n} 칼럼" href="${link('/rss.xml')}"><link rel="stylesheet" href="/assets/subsites/studio.css?v=20261009"><link rel="stylesheet" href="/assets/subsites/features.css?v=20261009"><link rel="stylesheet" href="/assets/subsites/agency.css?v=20261010d"><link rel="stylesheet" href="/assets/subsites/ribbon.css?v=20261010d"><link rel="stylesheet" href="/assets/subsites/readability.css?v=20261010"><script src="/assets/subsites/tools-popup.js?v=20261010b" defer></script><link rel="stylesheet" href="/assets/subsites/industry-polish.css?v=20261010"><script src="/assets/subsites/column-board.js?v=20261010" defer></script><link rel="stylesheet" href="/assets/subsites/video.css?v=20261010b"><script src="/assets/subsites/video.js?v=20261010" defer></script><script src="/assets/subsites/agency.js?v=20261010c" defer></script><script type="application/ld+json">${scriptJSON({'@context':'https://schema.org','@graph':graph})}</script><script src="/assets/subsites/studio.js?v=20261009" defer></script><script src="/assets/subsites/features.js?v=20261010" defer></script></head><body class="theme-${d.theme}" data-site="${k}">${nav}${body}${k==='interior'?companyFooter.replace('기존 아비컴퍼니 고객 후기','인테리어 업체 후기').replace('아비컴퍼니 기존 고객 후기 · 전문직','홈페이지 제작 후기 · 개별 사례').replace('href="https://aubcompany.com/">기존 홈페이지 후기 보기 ↗','href="https://interior-f5.com/" target="_blank" rel="noopener">새로고침 인테리어 홈페이지 ↗'):companyFooter}${contactDock(chat)}${toolDialog(k)}</body></html>`;
}
export function sitemap(k){const urls=[['/','2026-10-09'],['/column/','2026-10-09'],...(articles[k]||[]).map(a=>[`/column/${a.slug}/`,a.dateModified])];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(([p,d])=>`<url><loc>https://${k}.aubcompany.com${p}</loc><lastmod>${d}</lastmod></url>`).join('')}</urlset>`;}
export function rss(k){return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(sites[k].n)} 칼럼 | 아비컴퍼니</title><link>https://${k}.aubcompany.com/column/</link><description>${esc(sites[k].d)}</description><language>ko-KR</language>${(articles[k]||[]).map(a=>`<item><title>${esc(a.title)}</title><link>https://${k}.aubcompany.com/column/${a.slug}/</link><guid isPermaLink="true">https://${k}.aubcompany.com/column/${a.slug}/</guid><description>${esc(a.description)}</description><pubDate>${new Date(a.datePublished+'T09:00:00+09:00').toUTCString()}</pubDate></item>`).join('')}</channel></rss>`;}
